theme: jekyll-theme-primer
encding: utf-8
plugins:
  - 'jekyll-twitter-plugin'
  - 'jekyll-seo-tag'
repository: mixi-git-challenge/publications
destination: docs
baseurl: publications
exclude:
  - vendor
  - dev
  - Gemfile
  - Gemfile.lock
include:
  - .nojekyll
lang: ja-JP

title: git challenge publications
twitter:
  username: hr_mixi
  card: summary_large_image

readme_index:
  with_frontmatter: true

google_analytics: UA-6252589-15
