name: GitHub Pages

on:
  pull_request: null
  push:
    branches:
    - master
    paths-ignore:
    - "docs/**"

jobs:
  build:
    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 1
    - uses: actions/setup-ruby@v1
      with:
        version: 2.6.x
    - name: bundle install
      run: bundle install
    - name: jekyll build
      run: bundle exec jekyll build
      env:
        JEKYLL_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: deploy
      if: github.ref == 'refs/heads/master'
      use: docker://buildpack-deps:18.04-scm
      env:
        DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
        GIT_NAME: Bot
        GIT_EMAIL: example@example.com
      env:
        DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
        GIT_NAME: Bot
        GIT_EMAIL: example@example.com
        TARGET_BRANCH: master
      with:
        entrypoint: /bin/bash
        args: .github/scripts/deploy.bash
